// Generated by Selenium IDE
const { Builder, By, until, Key } = require('selenium-webdriver')
const assert = require('assert')

describe('authorization_correct', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('authorization_correct', async function() {
    await driver.get("https://incognitohr.com/en")
    await driver.manage().window().setRect({ width: 1920, height: 1080})
    await driver.findElement(By.linkText("Sign in")).click()
    await driver.findElement(By.id("loginform-identity")).click()
    await driver.findElement(By.id("loginform-identity")).sendKeys("artur@osi.in.ua")
    await driver.findElement(By.id("loginform-password")).click()
    await driver.findElement(By.id("loginform-password")).sendKeys(Key.SPACE, Key.SPACE, Key.SPACE, Key.SPACE, Key.SPACE, '1')
    await driver.findElement(By.name("login-button")).click()
    await driver.sleep(2000)
    await driver.executeScript(`document.querySelector("a[href='/en/user/sign-in/logout']").scrollIntoView()`);
    await driver.sleep(2000)

    await driver.findElement(By.linkText("Logout")).click()

    {
      const elements = await driver.findElements(By.xpath('//*[@id="navbarSupportedContent"]/div[1]/a[1]'))
      assert(elements.length)
    }
    await driver.sleep(2000)
  })
})
