// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const formatURL = require('../lib/formatUrl')

describe('auth', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('auth', async function() {
    console.log(driver.prototype)
    await driver.get("https://dev.incognitohr.com/en")
    await driver.manage().window().setRect({ width: 1920, height: 1080})
    await driver.findElement(By.linkText("Sign in")).click()
    await driver.findElement(By.id("loginform-identity")).click()
    await driver.findElement(By.id("loginform-identity")).sendKeys("artu@osi.in.ua")
    await driver.findElement(By.id("loginform-password")).click()
    await driver.findElement(By.id("loginform-password")).sendKeys("1111111")
    await driver.findElement(By.name("login-button")).click()
    // await driver.sleep(15000)

    {
      const elements = await driver.findElements(By.css(".alert"))
      assert(elements.length)
    }
  })
})
